version: '3'
# Specifies the version of Docker Compose to use. Version 3 is widely used and recommended.

services:
  # Defines the different services (containers) that make up your application.

  nginx:
    # This is the service name, here it's 'nginx', but you can name it anything.

    image: nginx:latest
    # Specifies which Docker image to use for this service. 
    # In this case, it uses the latest version of the official Nginx image.

    ports:
      - '80:80'
      # Maps the port from inside the Docker container to your host.
      # Format: [HOST_PORT]:[CONTAINER_PORT]. Here, it maps port 80 of the container to port 80 on the host.

    volumes:
      - ./site1:/usr/share/nginx/html/site1
      - ./site2:/usr/share/nginx/html/site2
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # Mounts directories from your host to the Docker container.
      # Format: [HOST_PATH]:[CONTAINER_PATH]. 
      # Here, it mounts 'site1' and 'site2' directories and the 'default.conf' file from the host to specific paths in the container.

    networks:
      - newbridge
      # Specifies the network the container is connected to. 
      # Here, the service uses a custom network named 'newbridge'.

    restart: always
    # Sets the restart policy for the container. 
    # 'always' means the container will restart automatically if it stops or crashes.

networks:
  newbridge:
  # Defines a custom network named 'newbridge'. 
  # Containers in the same network can communicate with each other using their service names.

